In [92]:
import pandas as pd

In [93]:
urlLengthRailways = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/rail_if_line_na$defaultview/1.0?compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'
urlNumberPassengersPerState = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/rail_pa_total$defaultview/1.0?compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'

In [94]:
df = pd.read_csv(urlNumberPassengersPerState, sep=",", compression="gzip")
df.head()

dfLength = pd.read_csv(urlLengthRailways, sep=",", compression="gzip")

In [95]:
df.describe()

       TIME_PERIOD     OBS_VALUE  OBS_FLAG
count   621.000000  5.660000e+02       0.0
mean   2020.064412  1.466228e+05       NaN
std       2.661986  4.010568e+05       NaN
min    2016.000000  8.000000e+00       NaN
25%    2018.000000  1.481500e+03       NaN
50%    2020.000000  1.354050e+04       NaN
75%    2022.000000  7.810000e+04       NaN
max    2025.000000  2.938023e+06       NaN

In [96]:
df["freq"].unique

<bound method Series.unique of 0      Annual
1      Annual
2      Annual
3      Annual
4      Annual
        ...
616    Annual
617    Annual
618    Annual
619    Annual
620    Annual
Name: freq, Length: 621, dtype: object>

In [97]:
df["freq"].value_counts()

freq
Annual    621
Name: count, dtype: int64

In [98]:
# freq sempre Annual quindi possiamo toglierla

In [99]:
df = df.drop("DATAFLOW", axis=1)

In [100]:
df.head()

,LAST UPDATE,freq,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2016,12497.0,NaN,NaN
1,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2017,12562.0,NaN,NaN
2,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2018,13122.0,NaN,NaN
3,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2019,13252.0,NaN,NaN
4,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2020,7375.0,NaN,NaN

In [101]:
df = df.drop("LAST UPDATE", axis=1)

In [102]:
df = df.drop("freq", axis=1)

In [103]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,Millions of passenger-kilometres,Austria,2016,12497.0,NaN,NaN
1,Millions of passenger-kilometres,Austria,2017,12562.0,NaN,NaN
2,Millions of passenger-kilometres,Austria,2018,13122.0,NaN,NaN
3,Millions of passenger-kilometres,Austria,2019,13252.0,NaN,NaN
4,Millions of passenger-kilometres,Austria,2020,7375.0,NaN,NaN
...,...,...,...,...,...,...
616,Thousand passengers,Ukraine,2023,64930.0,NaN,NaN
617,Thousand passengers,United Kingdom,2016,1772563.0,NaN,NaN
618,Thousand passengers,United Kingdom,2017,1757359.0,NaN,NaN
619,Thousand passengers,United Kingdom,2018,1783232.0,NaN,NaN
620,Thousand passengers,United Kingdom,2019,1836886.0,NaN,NaN

In [104]:
df["unit"].value_counts()

unit
Millions of passenger-kilometres    319
Thousand passengers                 302
Name: count, dtype: int64

In [105]:
# Abbiamo due unite diverse millioni di passegger x chilometri e migliaia di passeggeri.
# Dobbiamo sceglierne una

In [106]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,Millions of passenger-kilometres,Austria,2016,12497.0,NaN,NaN
1,Millions of passenger-kilometres,Austria,2017,12562.0,NaN,NaN
2,Millions of passenger-kilometres,Austria,2018,13122.0,NaN,NaN
3,Millions of passenger-kilometres,Austria,2019,13252.0,NaN,NaN
4,Millions of passenger-kilometres,Austria,2020,7375.0,NaN,NaN
...,...,...,...,...,...,...
616,Thousand passengers,Ukraine,2023,64930.0,NaN,NaN
617,Thousand passengers,United Kingdom,2016,1772563.0,NaN,NaN
618,Thousand passengers,United Kingdom,2017,1757359.0,NaN,NaN
619,Thousand passengers,United Kingdom,2018,1783232.0,NaN,NaN
620,Thousand passengers,United Kingdom,2019,1836886.0,NaN,NaN

In [107]:
df = df.sort_values('OBS_VALUE')

In [108]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
176,Millions of passenger-kilometres,Liechtenstein,2020,8.0,NaN,NaN
177,Millions of passenger-kilometres,Liechtenstein,2021,12.0,NaN,NaN
13,Millions of passenger-kilometres,Bosnia and Herzegovina,2020,14.0,NaN,NaN
173,Millions of passenger-kilometres,Liechtenstein,2017,15.0,NaN,NaN
172,Millions of passenger-kilometres,Liechtenstein,2016,16.0,NaN,NaN
...,...,...,...,...,...,...
552,Thousand passengers,Poland,2020,NaN,NaN,C
553,Thousand passengers,Poland,2021,NaN,NaN,C
554,Thousand passengers,Poland,2022,NaN,NaN,C
555,Thousand passengers,Poland,2023,NaN,NaN,C
556,Thousand passengers,Poland,2024,NaN,NaN,C

In [109]:
df["OBS_VALUE"].isna().sum()

np.int64(55)

In [110]:
df["CONF_STATUS"].unique

<bound method Series.unique of 176    NaN
177    NaN
13     NaN
173    NaN
172    NaN
      ...
552      C
553      C
554      C
555      C
556      C
Name: CONF_STATUS, Length: 621, dtype: object>

In [111]:
# Rimuovo OBS_VALUE = NaN

In [112]:
df = df.dropna(subset=["OBS_VALUE"])

In [113]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
176,Millions of passenger-kilometres,Liechtenstein,2020,8.0,NaN,NaN
177,Millions of passenger-kilometres,Liechtenstein,2021,12.0,NaN,NaN
13,Millions of passenger-kilometres,Bosnia and Herzegovina,2020,14.0,NaN,NaN
173,Millions of passenger-kilometres,Liechtenstein,2017,15.0,NaN,NaN
172,Millions of passenger-kilometres,Liechtenstein,2016,16.0,NaN,NaN
...,...,...,...,...,...,...
374,Thousand passengers,Germany,2016,2813782.0,NaN,NaN
375,Thousand passengers,Germany,2017,2831443.0,NaN,NaN
376,Thousand passengers,Germany,2018,2880558.0,NaN,NaN
382,Thousand passengers,Germany,2024,2929624.0,NaN,NaN
377,Thousand passengers,Germany,2019,2938023.0,NaN,NaN

In [114]:
df["OBS_FLAG"].value_counts()

Series([], Name: count, dtype: int64)

In [115]:
df["unit"].value_counts()

unit
Millions of passenger-kilometres    288
Thousand passengers                 278
Name: count, dtype: int64

In [116]:
df = df.drop("OBS_FLAG", axis=1)

In [117]:
df = df.drop("CONF_STATUS", axis=1)

In [118]:
df
df.columns
dfLength.columns

Index(['DATAFLOW', 'LAST UPDATE', 'freq', 'unit', 'tra_infr', 'tra_meas',
       'geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS'],
      dtype='object')

In [119]:
dfLength.columns

Index(['DATAFLOW', 'LAST UPDATE', 'freq', 'unit', 'tra_infr', 'tra_meas',
       'geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS'],
      dtype='object')

In [120]:
dfLength["unit"].value_counts()
df[df['geo'] == 'Germany']

                                 unit      geo  TIME_PERIOD  OBS_VALUE
60   Millions of passenger-kilometres  Germany         2021    57518.0
59   Millions of passenger-kilometres  Germany         2020    57787.0
61   Millions of passenger-kilometres  Germany         2022    92313.0
55   Millions of passenger-kilometres  Germany         2016    95465.0
56   Millions of passenger-kilometres  Germany         2017    95529.0
57   Millions of passenger-kilometres  Germany         2018    98161.0
58   Millions of passenger-kilometres  Germany         2019   100252.0
62   Millions of passenger-kilometres  Germany         2023   101408.0
63   Millions of passenger-kilometres  Germany         2024   109135.0
378               Thousand passengers  Germany         2020  1752198.0
379               Thousand passengers  Germany         2021  1761388.0
380               Thousand passengers  Germany         2022  2505856.0
381               Thousand passengers  Germany         2023  2727923.0
374               Thousand passengers  Germany         2016  2813782.0
375               Thousand passengers  Germany         2017  2831443.0
376               Thousand passengers  Germany         2018  2880558.0
382               Thousand passengers  Germany         2024  2929624.0
377               Thousand passengers  Germany         2019  2938023.0

In [121]:
df[df['unit'] == 'Millions of passenger-kilometres']

,unit,geo,TIME_PERIOD,OBS_VALUE
176,Millions of passenger-kilometres,Liechtenstein,2020,8.0
177,Millions of passenger-kilometres,Liechtenstein,2021,12.0
13,Millions of passenger-kilometres,Bosnia and Herzegovina,2020,14.0
173,Millions of passenger-kilometres,Liechtenstein,2017,15.0
172,Millions of passenger-kilometres,Liechtenstein,2016,16.0
...,...,...,...,...
111,Millions of passenger-kilometres,European Union - 27 countries (from 2020),2023,429575.0
102,Millions of passenger-kilometres,European Union - 27 countries (2007-2013),2018,467983.0
115,Millions of passenger-kilometres,European Union - 28 countries (2013-2020),2018,468730.0
103,Millions of passenger-kilometres,European Union - 27 countries (2007-2013),2019,483301.0
116,Millions of passenger-kilometres,European Union - 28 countries (2013-2020),2019,484025.0

In [122]:
df[df['unit'] == 'Thousand passengers']

                    unit                     geo  TIME_PERIOD  OBS_VALUE
528  Thousand passengers         North Macedonia         2025      178.0
332  Thousand passengers  Bosnia and Herzegovina         2020      181.0
527  Thousand passengers         North Macedonia         2024      238.0
333  Thousand passengers  Bosnia and Herzegovina         2021      250.0
524  Thousand passengers         North Macedonia         2021      252.0
..                   ...                     ...          ...        ...
374  Thousand passengers                 Germany         2016  2813782.0
375  Thousand passengers                 Germany         2017  2831443.0
376  Thousand passengers                 Germany         2018  2880558.0
382  Thousand passengers                 Germany         2024  2929624.0
377  Thousand passengers                 Germany         2019  2938023.0

[278 rows x 4 columns]

In [123]:
# Tolgo dati totali paesi

In [124]:
df = df[~df["geo"].str.contains("European Union", na=False)]

In [125]:
# Tengo solo unit Thousand passengers

In [126]:
df = df[~df["unit"].str.contains("Millions of passenger-kilometres", na=False)]

In [127]:
df

                    unit                     geo  TIME_PERIOD  OBS_VALUE
528  Thousand passengers         North Macedonia         2025      178.0
332  Thousand passengers  Bosnia and Herzegovina         2020      181.0
527  Thousand passengers         North Macedonia         2024      238.0
333  Thousand passengers  Bosnia and Herzegovina         2021      250.0
524  Thousand passengers         North Macedonia         2021      252.0
..                   ...                     ...          ...        ...
374  Thousand passengers                 Germany         2016  2813782.0
375  Thousand passengers                 Germany         2017  2831443.0
376  Thousand passengers                 Germany         2018  2880558.0
382  Thousand passengers                 Germany         2024  2929624.0
377  Thousand passengers                 Germany         2019  2938023.0

[278 rows x 4 columns]

In [128]:
df = df.sort_values(["geo", "TIME_PERIOD"])

In [129]:
df.head(20)

                    unit                     geo  TIME_PERIOD  OBS_VALUE
319  Thousand passengers                 Austria         2016   286990.0
320  Thousand passengers                 Austria         2017   288503.0
321  Thousand passengers                 Austria         2018   307647.0
322  Thousand passengers                 Austria         2019   314892.0
323  Thousand passengers                 Austria         2020   191272.0
324  Thousand passengers                 Austria         2021   217501.0
325  Thousand passengers                 Austria         2022   292479.0
326  Thousand passengers                 Austria         2023   325362.0
327  Thousand passengers                 Austria         2024   348219.0
328  Thousand passengers  Bosnia and Herzegovina         2016      418.0
329  Thousand passengers  Bosnia and Herzegovina         2017      472.0
330  Thousand passengers  Bosnia and Herzegovina         2018      549.0
331  Thousand passengers  Bosnia and Herzegovina         2019      657.0
332  Thousand passengers  Bosnia and Herzegovina         2020      181.0
333  Thousand passengers  Bosnia and Herzegovina         2021      250.0
334  Thousand passengers  Bosnia and Herzegovina         2022      442.0
335  Thousand passengers  Bosnia and Herzegovina         2023      448.0
336  Thousand passengers  Bosnia and Herzegovina         2024      421.0
346  Thousand passengers                Bulgaria         2016    21425.0
347  Thousand passengers                Bulgaria         2017    21195.0

In [130]:
df = df.rename(columns={"OBS_VALUE": "Thousand_Passengers"})

In [131]:
df

                    unit             geo  TIME_PERIOD  Thousand_Passengers
319  Thousand passengers         Austria         2016             286990.0
320  Thousand passengers         Austria         2017             288503.0
321  Thousand passengers         Austria         2018             307647.0
322  Thousand passengers         Austria         2019             314892.0
323  Thousand passengers         Austria         2020             191272.0
..                   ...             ...          ...                  ...
616  Thousand passengers         Ukraine         2023              64930.0
617  Thousand passengers  United Kingdom         2016            1772563.0
618  Thousand passengers  United Kingdom         2017            1757359.0
619  Thousand passengers  United Kingdom         2018            1783232.0
620  Thousand passengers  United Kingdom         2019            1836886.0

[278 rows x 4 columns]

In [132]:
df = df.drop("unit", axis=1)

In [133]:
df

                geo  TIME_PERIOD  Thousand_Passengers
319         Austria         2016             286990.0
320         Austria         2017             288503.0
321         Austria         2018             307647.0
322         Austria         2019             314892.0
323         Austria         2020             191272.0
..              ...          ...                  ...
616         Ukraine         2023              64930.0
617  United Kingdom         2016            1772563.0
618  United Kingdom         2017            1757359.0
619  United Kingdom         2018            1783232.0
620  United Kingdom         2019            1836886.0

[278 rows x 3 columns]

In [134]:
dfLength

,DATAFLOW,LAST UPDATE,freq,unit,tra_infr,tra_meas,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Albania,2015,379.00,NaN,NaN
1,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Albania,2016,334.00,NaN,NaN
2,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Albania,2017,334.00,NaN,NaN
3,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Albania,2018,334.00,NaN,NaN
4,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Albania,2019,234.85,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
389,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Kosovo*,2018,246.35,NaN,NaN
390,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Kosovo*,2019,246.35,NaN,NaN
391,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Kosovo*,2020,246.35,NaN,NaN
392,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Kosovo*,2021,246.35,NaN,NaN
393,ESTAT:RAIL_IF_LINE_NA$DEFAULTVIEW(1.0),16/04/26 23:00:00,Annual,Kilometre,Total,Total,Kosovo*,2022,246.35,NaN,NaN

In [135]:
df = df.merge(
    dfLength[["geo", "TIME_PERIOD", "OBS_VALUE"]],
    on=["geo", "TIME_PERIOD"],
    how="left"
)

In [136]:
df

                geo  TIME_PERIOD  Thousand_Passengers  OBS_VALUE
0           Austria         2016             286990.0     5491.0
1           Austria         2017             288503.0     5527.0
2           Austria         2018             307647.0     5526.0
3           Austria         2019             314892.0     5615.0
4           Austria         2020             191272.0     5607.0
..              ...          ...                  ...        ...
273         Ukraine         2023              64930.0    19760.0
274  United Kingdom         2016            1772563.0    16253.0
275  United Kingdom         2017            1757359.0    16320.0
276  United Kingdom         2018            1783232.0    16289.0
277  United Kingdom         2019            1836886.0    16480.0

[278 rows x 4 columns]

In [137]:
df = df.rename(columns={"OBS_VALUE": "km_railways"})

In [138]:
df

                geo  TIME_PERIOD  Thousand_Passengers  km_railways
0           Austria         2016             286990.0       5491.0
1           Austria         2017             288503.0       5527.0
2           Austria         2018             307647.0       5526.0
3           Austria         2019             314892.0       5615.0
4           Austria         2020             191272.0       5607.0
..              ...          ...                  ...          ...
273         Ukraine         2023              64930.0      19760.0
274  United Kingdom         2016            1772563.0      16253.0
275  United Kingdom         2017            1757359.0      16320.0
276  United Kingdom         2018            1783232.0      16289.0
277  United Kingdom         2019            1836886.0      16480.0

[278 rows x 4 columns]

In [139]:
df[df['geo'] == 'Kosovo*']

Empty DataFrame
Columns: [geo, TIME_PERIOD, Thousand_Passengers, km_railways]
Index: []

In [140]:
df[df["geo"].str.contains("Kosovo", na=False)]

Empty DataFrame
Columns: [geo, TIME_PERIOD, Thousand_Passengers, km_railways]
Index: []

In [141]:
df.head(20)

                       geo  TIME_PERIOD  Thousand_Passengers  km_railways
0                  Austria         2016             286990.0       5491.0
1                  Austria         2017             288503.0       5527.0
2                  Austria         2018             307647.0       5526.0
3                  Austria         2019             314892.0       5615.0
4                  Austria         2020             191272.0       5607.0
5                  Austria         2021             217501.0       5603.0
6                  Austria         2022             292479.0       5575.0
7                  Austria         2023             325362.0       5577.0
8                  Austria         2024             348219.0       5624.0
9   Bosnia and Herzegovina         2016                418.0       1018.0
10  Bosnia and Herzegovina         2017                472.0       1018.0
11  Bosnia and Herzegovina         2018                549.0       1018.0
12  Bosnia and Herzegovina         2019                657.0       1018.0
13  Bosnia and Herzegovina         2020                181.0       1018.0
14  Bosnia and Herzegovina         2021                250.0       1018.0
15  Bosnia and Herzegovina         2022                442.0       1018.0
16  Bosnia and Herzegovina         2023                448.0       1025.0
17  Bosnia and Herzegovina         2024                421.0       1025.0
18                Bulgaria         2016              21425.0       4029.0
19                Bulgaria         2017              21195.0       4030.0

In [142]:
df["geo"].unique().size

33

In [143]:
dfTemp = (df.groupby("TIME_PERIOD"))

In [144]:
dfTemp

In [145]:
df_grouped = dfTemp.size().reset_index(name="count")

In [146]:
df_grouped

   TIME_PERIOD  count
0         2016     31
1         2017     31
2         2018     30
3         2019     30
4         2020     30
5         2021     29
6         2022     30
7         2023     30
8         2024     30
9         2025      7

In [147]:
dfTemp = (df.groupby("geo"))

In [148]:
df_grouped = dfTemp.size().reset_index(name="count")

In [149]:
df_grouped

                       geo  count
0                  Austria      9
1   Bosnia and Herzegovina      9
2                 Bulgaria     10
3                  Croatia     10
4                  Czechia      9
5                  Denmark      9
6                  Estonia      9
7                  Finland      9
8                   France      9
9                  Germany      9
10                  Greece      9
11                 Hungary      1
12                 Ireland      9
13                   Italy      9
14                  Latvia      9
15           Liechtenstein      9
16               Lithuania     10
17              Luxembourg      9
18              Montenegro      8
19             Netherlands      9
20         North Macedonia     10
21                  Norway     10
22                  Poland      2
23                Portugal      9
24                 Romania     10
25                Slovakia     10
26                Slovenia      9
27                   Spain      9
28                  Sweden      9
29             Switzerland      9
30                 Türkiye      9
31                 Ukraine      4
32          United Kingdom      4

In [150]:
df[df['geo'] == 'Poland']

        geo  TIME_PERIOD  Thousand_Passengers  km_railways
194  Poland         2016             285094.0      19132.0
195  Poland         2017             295394.0      19209.0

In [151]:
df[df['geo'] == 'Italy']

       geo  TIME_PERIOD  Thousand_Passengers  km_railways
111  Italy         2016             869199.0      16788.0
112  Italy         2017             864570.0      16787.0
113  Italy         2018             882243.0      16781.0
114  Italy         2019             898472.0      16779.0
115  Italy         2020             389883.0      16782.0
116  Italy         2021             491782.0      16832.0
117  Italy         2022             693604.0      16829.0
118  Italy         2023             814441.0      16832.0
119  Italy         2024             842822.0      16879.0

In [152]:
urlPopulation = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/demo_urespop$defaultview/1.0?compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'

In [153]:
dfPopulation = pd.read_csv(urlPopulation, sep=",", compression="gzip")

In [154]:
dfPopulation

,DATAFLOW,LAST UPDATE,freq,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,Austria,2016,8711500,e,NaN
1,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,Austria,2017,8752500,e,NaN
2,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,Austria,2018,8802000,e,NaN
3,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,Austria,2019,8842000,e,NaN
4,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,Austria,2020,8897000,e,NaN
...,...,...,...,...,...,...,...,...,...
292,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,Slovakia,2025,5456246,e,NaN
293,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,United Kingdom,2016,65341183,e,NaN
294,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,United Kingdom,2017,65808573,e,NaN
295,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,United Kingdom,2018,66238007,e,NaN
296,ESTAT:DEMO_URESPOP$DEFAULTVIEW(1.0),16/10/24 11:00:00,Annual,Number,United Kingdom,2019,66647112,e,NaN

In [155]:
dfPopulation = dfPopulation.drop("DATAFLOW", axis=1)
dfPopulation = dfPopulation.drop("LAST UPDATE", axis=1)
dfPopulation = dfPopulation.drop("freq", axis=1)
dfPopulation = dfPopulation.drop("unit", axis=1)

In [156]:
dfPopulation

                geo  TIME_PERIOD  OBS_VALUE OBS_FLAG  CONF_STATUS
0           Austria         2016    8711500        e          NaN
1           Austria         2017    8752500        e          NaN
2           Austria         2018    8802000        e          NaN
3           Austria         2019    8842000        e          NaN
4           Austria         2020    8897000        e          NaN
..              ...          ...        ...      ...          ...
292        Slovakia         2025    5456246        e          NaN
293  United Kingdom         2016   65341183        e          NaN
294  United Kingdom         2017   65808573        e          NaN
295  United Kingdom         2018   66238007        e          NaN
296  United Kingdom         2019   66647112        e          NaN

[297 rows x 5 columns]

In [157]:
dfPopulation["OBS_FLAG"].unique()

array(['e', 'b', nan, 'be'], dtype=object)

In [158]:
df = df.merge(
    dfPopulation[["geo", "TIME_PERIOD", "OBS_VALUE"]],
    on=["geo", "TIME_PERIOD"],
    how="left"
)

In [159]:
df

                geo  TIME_PERIOD  Thousand_Passengers  km_railways   OBS_VALUE
0           Austria         2016             286990.0       5491.0   8711500.0
1           Austria         2017             288503.0       5527.0   8752500.0
2           Austria         2018             307647.0       5526.0   8802000.0
3           Austria         2019             314892.0       5615.0   8842000.0
4           Austria         2020             191272.0       5607.0   8897000.0
..              ...          ...                  ...          ...         ...
273         Ukraine         2023              64930.0      19760.0         NaN
274  United Kingdom         2016            1772563.0      16253.0  65341183.0
275  United Kingdom         2017            1757359.0      16320.0  65808573.0
276  United Kingdom         2018            1783232.0      16289.0  66238007.0
277  United Kingdom         2019            1836886.0      16480.0  66647112.0

[278 rows x 5 columns]

In [160]:
df = df.rename(columns={"OBS_VALUE": "population"})

In [161]:
df

                geo  TIME_PERIOD  Thousand_Passengers  km_railways  population
0           Austria         2016             286990.0       5491.0   8711500.0
1           Austria         2017             288503.0       5527.0   8752500.0
2           Austria         2018             307647.0       5526.0   8802000.0
3           Austria         2019             314892.0       5615.0   8842000.0
4           Austria         2020             191272.0       5607.0   8897000.0
..              ...          ...                  ...          ...         ...
273         Ukraine         2023              64930.0      19760.0         NaN
274  United Kingdom         2016            1772563.0      16253.0  65341183.0
275  United Kingdom         2017            1757359.0      16320.0  65808573.0
276  United Kingdom         2018            1783232.0      16289.0  66238007.0
277  United Kingdom         2019            1836886.0      16480.0  66647112.0

[278 rows x 5 columns]

In [162]:
df[df.isna().any(axis=1)]

,geo,TIME_PERIOD,Thousand_Passengers,km_railways,population
9,Bosnia and Herzegovina,2016,418.0,1018.0,NaN
10,Bosnia and Herzegovina,2017,472.0,1018.0,NaN
11,Bosnia and Herzegovina,2018,549.0,1018.0,NaN
12,Bosnia and Herzegovina,2019,657.0,1018.0,NaN
13,Bosnia and Herzegovina,2020,181.0,1018.0,NaN
...,...,...,...,...,...
269,Türkiye,2024,24021.0,11417.0,NaN
270,Ukraine,2020,68332.0,19790.0,NaN
271,Ukraine,2021,81335.0,19731.0,NaN
272,Ukraine,2022,52690.0,19772.0,NaN
273,Ukraine,2023,64930.0,19760.0,NaN

In [163]:
df[df['geo'] == 'Italy']

       geo  TIME_PERIOD  Thousand_Passengers  km_railways  population
111  Italy         2016             869199.0      16788.0  61302519.0
112  Italy         2017             864570.0      16787.0  61219113.0
113  Italy         2018             882243.0      16781.0  61166142.0
114  Italy         2019             898472.0      16779.0  61068437.0
115  Italy         2020             389883.0      16782.0  60897891.0
116  Italy         2021             491782.0      16832.0  59862348.0
117  Italy         2022             693604.0      16829.0  59607184.0
118  Italy         2023             814441.0      16832.0  59691110.0
119  Italy         2024             842822.0      16879.0  59685948.0

In [164]:
gdpCapitaUrl = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/sdg_08_10/1.0/*.*.*.*?c[freq]=A&c[unit]=CLV20_EUR_HAB&c[na_item]=B1GQ&c[geo]=BE,BG,CZ,DK,DE,EE,IE,EL,ES,FR,HR,IT,CY,LV,LT,LU,HU,MT,NL,AT,PL,PT,RO,SI,SK,FI,SE,IS,NO,CH,AL,BA,EA19,ME,MK,RS,TR,UK&c[TIME_PERIOD]=2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025&compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'

In [165]:
dfCapita = pd.read_csv(gdpCapitaUrl, sep=",", compression="gzip")

In [166]:
dfCapita

,DATAFLOW,LAST UPDATE,freq,unit,na_item,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2000,2120,NaN,NaN
1,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2001,2330,NaN,NaN
2,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2002,2440,NaN,NaN
3,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2003,2580,NaN,NaN
4,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2004,2730,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
932,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2020,7340,NaN,NaN
933,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2021,8130,NaN,NaN
934,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2022,8490,NaN,NaN
935,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2023,8920,NaN,NaN
936,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2024,9220,NaN,NaN

In [167]:
dfCapita[dfCapita['geo'] == 'Italy']

,DATAFLOW,LAST UPDATE,freq,unit,na_item,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
506,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2000,31090,NaN,NaN
507,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2001,31690,NaN,NaN
508,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2002,31720,NaN,NaN
509,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2003,31570,NaN,NaN
510,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2004,31790,NaN,NaN
511,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2005,31850,NaN,NaN
512,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2006,32290,NaN,NaN
513,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2007,32570,NaN,NaN
514,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2008,31990,NaN,NaN
515,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2009,30110,NaN,NaN
516,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2010,30440,NaN,NaN
517,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2011,30550,NaN,NaN
518,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2012,29510,NaN,NaN
519,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2013,28920,NaN,NaN
520,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2014,28910,NaN,NaN
521,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2015,29210,NaN,NaN
522,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2016,29630,NaN,NaN
523,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2017,30160,NaN,NaN
524,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2018,30470,NaN,NaN
525,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2019,30680,NaN,NaN
526,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2020,28100,NaN,NaN
527,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2021,30760,NaN,NaN
528,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2022,32310,NaN,NaN
529,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2023,32630,NaN,NaN
530,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2024,32900,NaN,NaN
531,ESTAT:SDG_08_10(1.0),08/06/26 11:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2025,33080,e,NaN

In [168]:
df = df.merge(
    dfCapita[["geo", "TIME_PERIOD", "OBS_VALUE"]],
    on=["geo", "TIME_PERIOD"],
    how="left"
)

In [169]:
df

,geo,TIME_PERIOD,Thousand_Passengers,km_railways,population,OBS_VALUE
0,Austria,2016,286990.0,5491.0,8711500.0,43550.0
1,Austria,2017,288503.0,5527.0,8752500.0,44260.0
2,Austria,2018,307647.0,5526.0,8802000.0,45140.0
3,Austria,2019,314892.0,5615.0,8842000.0,45730.0
4,Austria,2020,191272.0,5607.0,8897000.0,42650.0
...,...,...,...,...,...,...
273,Ukraine,2023,64930.0,19760.0,NaN,NaN
274,United Kingdom,2016,1772563.0,16253.0,65341183.0,NaN
275,United Kingdom,2017,1757359.0,16320.0,65808573.0,NaN
276,United Kingdom,2018,1783232.0,16289.0,66238007.0,NaN
277,United Kingdom,2019,1836886.0,16480.0,66647112.0,NaN

In [170]:
df = df.rename(columns={"OBS_VALUE": "GDP_Capita"})

In [171]:
df

,geo,TIME_PERIOD,Thousand_Passengers,km_railways,population,GDP_Capita
0,Austria,2016,286990.0,5491.0,8711500.0,43550.0
1,Austria,2017,288503.0,5527.0,8752500.0,44260.0
2,Austria,2018,307647.0,5526.0,8802000.0,45140.0
3,Austria,2019,314892.0,5615.0,8842000.0,45730.0
4,Austria,2020,191272.0,5607.0,8897000.0,42650.0
...,...,...,...,...,...,...
273,Ukraine,2023,64930.0,19760.0,NaN,NaN
274,United Kingdom,2016,1772563.0,16253.0,65341183.0,NaN
275,United Kingdom,2017,1757359.0,16320.0,65808573.0,NaN
276,United Kingdom,2018,1783232.0,16289.0,66238007.0,NaN
277,United Kingdom,2019,1836886.0,16480.0,66647112.0,NaN