In [1]:
import pandas as pd

In [2]:
urlLengthRailways = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/rail_if_line_na/1.0?compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'
urlNumberPassengersPerState = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/rail_pa_total/1.0?compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'

In [3]:
df = pd.read_csv(urlNumberPassengersPerState, sep=",", compression="gzip")
df.head()

dfLength = pd.read_csv(urlLengthRailways, sep=",", compression="gzip")

In [4]:
df.describe()

       TIME_PERIOD     OBS_VALUE  OBS_FLAG
count  1377.000000  1.276000e+03       0.0
mean   2014.374728  1.511032e+05       NaN
std       6.024215  3.944371e+05       NaN
min    2004.000000  1.000000e+00       NaN
25%    2009.000000  2.402750e+03       NaN
50%    2015.000000  1.570650e+04       NaN
75%    2020.000000  8.427400e+04       NaN
max    2025.000000  2.938023e+06       NaN

In [5]:
df["freq"].unique

<bound method Series.unique of 0       Annual
1       Annual
2       Annual
3       Annual
4       Annual
         ...
1372    Annual
1373    Annual
1374    Annual
1375    Annual
1376    Annual
Name: freq, Length: 1377, dtype: str>

In [6]:
df["freq"].value_counts()

freq
Annual    1377
Name: count, dtype: int64

In [7]:
# freq sempre Annual quindi possiamo toglierla

In [8]:
df = df.drop("DATAFLOW", axis=1)

In [9]:
df.head()

,LAST UPDATE,freq,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2004,8274.0,NaN,NaN
1,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2005,8685.0,NaN,NaN
2,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2006,8907.0,NaN,NaN
3,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2007,9167.0,NaN,NaN
4,02/06/26 23:00:00,Annual,Millions of passenger-kilometres,Austria,2008,10365.0,NaN,NaN

In [10]:
df = df.drop("LAST UPDATE", axis=1)

In [11]:
df = df.drop("freq", axis=1)

In [12]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,Millions of passenger-kilometres,Austria,2004,8274.0,NaN,NaN
1,Millions of passenger-kilometres,Austria,2005,8685.0,NaN,NaN
2,Millions of passenger-kilometres,Austria,2006,8907.0,NaN,NaN
3,Millions of passenger-kilometres,Austria,2007,9167.0,NaN,NaN
4,Millions of passenger-kilometres,Austria,2008,10365.0,NaN,NaN
...,...,...,...,...,...,...
1372,Thousand passengers,United Kingdom,2015,1741562.0,NaN,NaN
1373,Thousand passengers,United Kingdom,2016,1772563.0,NaN,NaN
1374,Thousand passengers,United Kingdom,2017,1757359.0,NaN,NaN
1375,Thousand passengers,United Kingdom,2018,1783232.0,NaN,NaN
1376,Thousand passengers,United Kingdom,2019,1836886.0,NaN,NaN

In [13]:
df["unit"].value_counts()

unit
Millions of passenger-kilometres    710
Thousand passengers                 667
Name: count, dtype: int64

In [14]:
# Abbiamo due unite diverse millioni di passegger x chilometri e migliaia di passeggeri.
# Dobbiamo sceglierne una

In [15]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,Millions of passenger-kilometres,Austria,2004,8274.0,NaN,NaN
1,Millions of passenger-kilometres,Austria,2005,8685.0,NaN,NaN
2,Millions of passenger-kilometres,Austria,2006,8907.0,NaN,NaN
3,Millions of passenger-kilometres,Austria,2007,9167.0,NaN,NaN
4,Millions of passenger-kilometres,Austria,2008,10365.0,NaN,NaN
...,...,...,...,...,...,...
1372,Thousand passengers,United Kingdom,2015,1741562.0,NaN,NaN
1373,Thousand passengers,United Kingdom,2016,1772563.0,NaN,NaN
1374,Thousand passengers,United Kingdom,2017,1757359.0,NaN,NaN
1375,Thousand passengers,United Kingdom,2018,1783232.0,NaN,NaN
1376,Thousand passengers,United Kingdom,2019,1836886.0,NaN,NaN

In [16]:
df = df.sort_values('OBS_VALUE')

In [17]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
389,Millions of passenger-kilometres,Liechtenstein,2007,1.0,NaN,NaN
388,Millions of passenger-kilometres,Liechtenstein,2006,1.0,NaN,NaN
391,Millions of passenger-kilometres,Liechtenstein,2009,1.0,NaN,NaN
392,Millions of passenger-kilometres,Liechtenstein,2010,1.0,NaN,NaN
396,Millions of passenger-kilometres,Liechtenstein,2014,1.0,NaN,NaN
...,...,...,...,...,...,...
1224,Thousand passengers,Poland,2020,NaN,NaN,C
1225,Thousand passengers,Poland,2021,NaN,NaN,C
1226,Thousand passengers,Poland,2022,NaN,NaN,C
1227,Thousand passengers,Poland,2023,NaN,NaN,C
1228,Thousand passengers,Poland,2024,NaN,NaN,C

In [18]:
df["OBS_VALUE"].isna().sum()

np.int64(101)

In [19]:
df['CONF_STATUS'].unique()

<StringArray>
[nan, 'C']
Length: 2, dtype: str

In [20]:
# Rimuovo OBS_VALUE = NaN

In [21]:
# df = df.dropna(subset=["OBS_VALUE"])
# Non rimuoviamo gli NA per poter fare interpolazione dei dati mancanti dopo

In [22]:
df

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
389,Millions of passenger-kilometres,Liechtenstein,2007,1.0,NaN,NaN
388,Millions of passenger-kilometres,Liechtenstein,2006,1.0,NaN,NaN
391,Millions of passenger-kilometres,Liechtenstein,2009,1.0,NaN,NaN
392,Millions of passenger-kilometres,Liechtenstein,2010,1.0,NaN,NaN
396,Millions of passenger-kilometres,Liechtenstein,2014,1.0,NaN,NaN
...,...,...,...,...,...,...
1224,Thousand passengers,Poland,2020,NaN,NaN,C
1225,Thousand passengers,Poland,2021,NaN,NaN,C
1226,Thousand passengers,Poland,2022,NaN,NaN,C
1227,Thousand passengers,Poland,2023,NaN,NaN,C
1228,Thousand passengers,Poland,2024,NaN,NaN,C

In [23]:
df["OBS_FLAG"].value_counts()

Series([], Name: count, dtype: int64)

In [24]:
df["unit"].value_counts()

unit
Millions of passenger-kilometres    710
Thousand passengers                 667
Name: count, dtype: int64

In [25]:
df = df.drop("OBS_FLAG", axis=1)

In [26]:
df = df.drop("CONF_STATUS", axis=1)

In [27]:
df = df[df['TIME_PERIOD'] < 2025]

In [28]:
df.columns

Index(['unit', 'geo', 'TIME_PERIOD', 'OBS_VALUE'], dtype='str')

In [29]:
dfLength.columns

Index(['DATAFLOW', 'LAST UPDATE', 'freq', 'unit', 'tra_infr', 'tra_meas',
       'geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS'],
      dtype='str')

In [30]:
dfLength["unit"].value_counts()

unit
Kilometre    12556
Name: count, dtype: int64

In [31]:
df[df['geo'] == 'Germany']

                                 unit      geo  TIME_PERIOD  OBS_VALUE
127  Millions of passenger-kilometres  Germany         2021    57518.0
126  Millions of passenger-kilometres  Germany         2020    57787.0
111  Millions of passenger-kilometres  Germany         2005    74944.0
110  Millions of passenger-kilometres  Germany         2004    75903.0
112  Millions of passenger-kilometres  Germany         2006    78735.0
113  Millions of passenger-kilometres  Germany         2007    79098.0
115  Millions of passenger-kilometres  Germany         2009    81206.0
114  Millions of passenger-kilometres  Germany         2008    82428.0
116  Millions of passenger-kilometres  Germany         2010    82837.0
117  Millions of passenger-kilometres  Germany         2011    89316.0
119  Millions of passenger-kilometres  Germany         2013    89450.0
120  Millions of passenger-kilometres  Germany         2014    90978.0
121  Millions of passenger-kilometres  Germany         2015    91050.0
128  Millions of passenger-kilometres  Germany         2022    92313.0
118  Millions of passenger-kilometres  Germany         2012    93918.0
122  Millions of passenger-kilometres  Germany         2016    95465.0
123  Millions of passenger-kilometres  Germany         2017    95529.0
124  Millions of passenger-kilometres  Germany         2018    98161.0
125  Millions of passenger-kilometres  Germany         2019   100252.0
129  Millions of passenger-kilometres  Germany         2023   101408.0
130  Millions of passenger-kilometres  Germany         2024   109135.0
836               Thousand passengers  Germany         2020  1752198.0
837               Thousand passengers  Germany         2021  1761388.0
820               Thousand passengers  Germany         2004  2091268.0
821               Thousand passengers  Germany         2005  2130469.0
823               Thousand passengers  Germany         2007  2226952.0
822               Thousand passengers  Germany         2006  2228926.0
825               Thousand passengers  Germany         2009  2323243.0
824               Thousand passengers  Germany         2008  2336683.0
826               Thousand passengers  Germany         2010  2368375.0
838               Thousand passengers  Germany         2022  2505856.0
827               Thousand passengers  Germany         2011  2530284.0
828               Thousand passengers  Germany         2012  2564498.0
829               Thousand passengers  Germany         2013  2612764.0
831               Thousand passengers  Germany         2015  2684908.0
830               Thousand passengers  Germany         2014  2693080.0
839               Thousand passengers  Germany         2023  2727923.0
832               Thousand passengers  Germany         2016  2813782.0
833               Thousand passengers  Germany         2017  2831443.0
834               Thousand passengers  Germany         2018  2880558.0
840               Thousand passengers  Germany         2024  2929624.0
835               Thousand passengers  Germany         2019  2938023.0

In [32]:
df[df['unit'] == 'Millions of passenger-kilometres']

                                 unit            geo  TIME_PERIOD  OBS_VALUE
389  Millions of passenger-kilometres  Liechtenstein         2007        1.0
388  Millions of passenger-kilometres  Liechtenstein         2006        1.0
391  Millions of passenger-kilometres  Liechtenstein         2009        1.0
392  Millions of passenger-kilometres  Liechtenstein         2010        1.0
396  Millions of passenger-kilometres  Liechtenstein         2014        1.0
..                                ...            ...          ...        ...
557  Millions of passenger-kilometres         Poland         2020        NaN
558  Millions of passenger-kilometres         Poland         2021        NaN
559  Millions of passenger-kilometres         Poland         2022        NaN
560  Millions of passenger-kilometres         Poland         2023        NaN
561  Millions of passenger-kilometres         Poland         2024        NaN

[703 rows x 4 columns]

In [33]:
df[df['unit'] == 'Thousand passengers']

                     unit            geo  TIME_PERIOD  OBS_VALUE
1061  Thousand passengers  Liechtenstein         2013       96.0
1058  Thousand passengers  Liechtenstein         2010       96.0
1060  Thousand passengers  Liechtenstein         2012       96.0
1059  Thousand passengers  Liechtenstein         2011       96.0
1057  Thousand passengers  Liechtenstein         2009       97.0
...                   ...            ...          ...        ...
1224  Thousand passengers         Poland         2020        NaN
1225  Thousand passengers         Poland         2021        NaN
1226  Thousand passengers         Poland         2022        NaN
1227  Thousand passengers         Poland         2023        NaN
1228  Thousand passengers         Poland         2024        NaN

[660 rows x 4 columns]

In [34]:
# Tolgo dati totali paesi

In [35]:
df = df[~df["geo"].str.contains("European Union", na=False)]

In [36]:
# Tengo solo unit Thousand passengers

In [37]:
df = df[~df["unit"].str.contains("Thousand passengers", na=False)]

In [38]:
df

                                 unit            geo  TIME_PERIOD  OBS_VALUE
389  Millions of passenger-kilometres  Liechtenstein         2007        1.0
388  Millions of passenger-kilometres  Liechtenstein         2006        1.0
391  Millions of passenger-kilometres  Liechtenstein         2009        1.0
392  Millions of passenger-kilometres  Liechtenstein         2010        1.0
396  Millions of passenger-kilometres  Liechtenstein         2014        1.0
..                                ...            ...          ...        ...
557  Millions of passenger-kilometres         Poland         2020        NaN
558  Millions of passenger-kilometres         Poland         2021        NaN
559  Millions of passenger-kilometres         Poland         2022        NaN
560  Millions of passenger-kilometres         Poland         2023        NaN
561  Millions of passenger-kilometres         Poland         2024        NaN

[659 rows x 4 columns]

In [39]:
df = df.sort_values(["geo", "TIME_PERIOD"])

In [40]:
df.head(20)

                                unit      geo  TIME_PERIOD  OBS_VALUE
0   Millions of passenger-kilometres  Austria         2004     8274.0
1   Millions of passenger-kilometres  Austria         2005     8685.0
2   Millions of passenger-kilometres  Austria         2006     8907.0
3   Millions of passenger-kilometres  Austria         2007     9167.0
4   Millions of passenger-kilometres  Austria         2008    10365.0
5   Millions of passenger-kilometres  Austria         2009    10184.0
6   Millions of passenger-kilometres  Austria         2010    10263.0
7   Millions of passenger-kilometres  Austria         2011    10778.0
8   Millions of passenger-kilometres  Austria         2012    11211.0
9   Millions of passenger-kilometres  Austria         2013    11804.0
10  Millions of passenger-kilometres  Austria         2014    11981.0
11  Millions of passenger-kilometres  Austria         2015    12104.0
12  Millions of passenger-kilometres  Austria         2016    12497.0
13  Millions of passenger-kilometres  Austria         2017    12562.0
14  Millions of passenger-kilometres  Austria         2018    13122.0
15  Millions of passenger-kilometres  Austria         2019    13252.0
16  Millions of passenger-kilometres  Austria         2020     7375.0
17  Millions of passenger-kilometres  Austria         2021     8447.0
18  Millions of passenger-kilometres  Austria         2022    12855.0
19  Millions of passenger-kilometres  Austria         2023    14435.0

In [41]:
df = df.rename(columns={"OBS_VALUE": "Passengers_Mil_KM"})

In [42]:
df

,unit,geo,TIME_PERIOD,Passengers_Mil_KM
0,Millions of passenger-kilometres,Austria,2004,8274.0
1,Millions of passenger-kilometres,Austria,2005,8685.0
2,Millions of passenger-kilometres,Austria,2006,8907.0
3,Millions of passenger-kilometres,Austria,2007,9167.0
4,Millions of passenger-kilometres,Austria,2008,10365.0
...,...,...,...,...
705,Millions of passenger-kilometres,United Kingdom,2015,66594.0
706,Millions of passenger-kilometres,United Kingdom,2016,68010.0
707,Millions of passenger-kilometres,United Kingdom,2017,68912.0
708,Millions of passenger-kilometres,United Kingdom,2018,69706.0
709,Millions of passenger-kilometres,United Kingdom,2019,71823.0

In [43]:
df = df.drop("unit", axis=1)

In [44]:
df

                geo  TIME_PERIOD  Passengers_Mil_KM
0           Austria         2004             8274.0
1           Austria         2005             8685.0
2           Austria         2006             8907.0
3           Austria         2007             9167.0
4           Austria         2008            10365.0
..              ...          ...                ...
705  United Kingdom         2015            66594.0
706  United Kingdom         2016            68010.0
707  United Kingdom         2017            68912.0
708  United Kingdom         2018            69706.0
709  United Kingdom         2019            71823.0

[659 rows x 3 columns]

In [45]:
dfLength[dfLength['geo'] == 'Austria']

,DATAFLOW,LAST UPDATE,freq,unit,tra_infr,tra_meas,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
33,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Electrified railway lines,Freight only,Austria,1999,0.0,NaN,NaN
34,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Electrified railway lines,Freight only,Austria,2000,0.0,NaN,NaN
35,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Electrified railway lines,Freight only,Austria,2001,0.0,NaN,NaN
36,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Electrified railway lines,Freight only,Austria,2002,0.0,NaN,NaN
37,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Electrified railway lines,Freight only,Austria,2003,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
11325,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Total,Total,Austria,2020,5607.0,NaN,NaN
11326,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Total,Total,Austria,2021,5603.0,NaN,NaN
11327,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Total,Total,Austria,2022,5575.0,NaN,NaN
11328,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Total,Total,Austria,2023,5577.0,NaN,NaN
11329,ESTAT:RAIL_IF_LINE_NA(1.0),10/06/26 23:00:00,Annual,Kilometre,Total,Total,Austria,2024,5624.0,NaN,NaN

In [46]:
dfLength['tra_meas'].unique()

<StringArray>
['Freight only', 'Passengers and freight', 'Passengers only', 'Total']
Length: 4, dtype: str

In [47]:
dfl1 = dfLength[(dfLength['tra_infr'] == 'Total') & ((dfLength['tra_meas'] == 'Passengers only') | (dfLength['tra_meas'] == 'Passengers and freight'))][['geo', 'TIME_PERIOD', 'OBS_VALUE']]
dfl1 = dfl1.groupby(['geo', 'TIME_PERIOD']).sum().reset_index()

In [48]:
dfl1[(dfl1['geo'] == 'Austria') & (dfl1['TIME_PERIOD'] == 2004)]

        geo  TIME_PERIOD  OBS_VALUE
38  Austria         2004     5675.0

In [49]:
df = df.merge(
    dfl1,
    on=["geo", "TIME_PERIOD"],
    how="left"
)

In [50]:
df

                geo  TIME_PERIOD  Passengers_Mil_KM  OBS_VALUE
0           Austria         2004             8274.0     5675.0
1           Austria         2005             8685.0     5691.0
2           Austria         2006             8907.0     5702.0
3           Austria         2007             9167.0     5702.0
4           Austria         2008            10365.0     5693.0
..              ...          ...                ...        ...
654  United Kingdom         2015            66594.0    14994.0
655  United Kingdom         2016            68010.0    14933.0
656  United Kingdom         2017            68912.0    14990.0
657  United Kingdom         2018            69706.0    15076.0
658  United Kingdom         2019            71823.0    15244.0

[659 rows x 4 columns]

In [51]:
df = df.rename(columns={"OBS_VALUE": "km_railways"})

In [52]:
df

                geo  TIME_PERIOD  Passengers_Mil_KM  km_railways
0           Austria         2004             8274.0       5675.0
1           Austria         2005             8685.0       5691.0
2           Austria         2006             8907.0       5702.0
3           Austria         2007             9167.0       5702.0
4           Austria         2008            10365.0       5693.0
..              ...          ...                ...          ...
654  United Kingdom         2015            66594.0      14994.0
655  United Kingdom         2016            68010.0      14933.0
656  United Kingdom         2017            68912.0      14990.0
657  United Kingdom         2018            69706.0      15076.0
658  United Kingdom         2019            71823.0      15244.0

[659 rows x 4 columns]

In [53]:
df[df['geo'] == 'Kosovo*']

Empty DataFrame
Columns: [geo, TIME_PERIOD, Passengers_Mil_KM, km_railways]
Index: []

In [54]:
df[df["geo"].str.contains("Kosovo", na=False)]

Empty DataFrame
Columns: [geo, TIME_PERIOD, Passengers_Mil_KM, km_railways]
Index: []

In [55]:
df.head(20)

        geo  TIME_PERIOD  Passengers_Mil_KM  km_railways
0   Austria         2004             8274.0       5675.0
1   Austria         2005             8685.0       5691.0
2   Austria         2006             8907.0       5702.0
3   Austria         2007             9167.0       5702.0
4   Austria         2008            10365.0       5693.0
5   Austria         2009            10184.0       5693.0
6   Austria         2010            10263.0       5828.0
7   Austria         2011            10778.0       5500.0
8   Austria         2012            11211.0       5566.0
9   Austria         2013            11804.0       5531.0
10  Austria         2014            11981.0       5531.0
11  Austria         2015            12104.0       5522.0
12  Austria         2016            12497.0       5491.0
13  Austria         2017            12562.0       5527.0
14  Austria         2018            13122.0       5526.0
15  Austria         2019            13252.0       5615.0
16  Austria         2020             7375.0       5607.0
17  Austria         2021             8447.0       5603.0
18  Austria         2022            12855.0       5575.0
19  Austria         2023            14435.0       5577.0

In [56]:
df["geo"].unique().size

34

In [57]:
dfTemp = (df.groupby("TIME_PERIOD"))

In [58]:
dfTemp

In [59]:
df_grouped = dfTemp.size().reset_index(name="count")

In [60]:
df_grouped

    TIME_PERIOD  count
0          2004     28
1          2005     28
2          2006     29
3          2007     29
4          2008     30
5          2009     30
6          2010     31
7          2011     31
8          2012     30
9          2013     32
10         2014     33
11         2015     33
12         2016     33
13         2017     33
14         2018     33
15         2019     33
16         2020     33
17         2021     32
18         2022     33
19         2023     33
20         2024     32

In [61]:
dfTemp = (df.groupby("geo"))

In [62]:
df_grouped = dfTemp.size().reset_index(name="count")

In [63]:
df_grouped

                       geo  count
0                  Austria     21
1                  Belgium     20
2   Bosnia and Herzegovina     11
3                 Bulgaria     19
4                  Croatia     21
5                  Czechia     21
6                  Denmark     21
7                  Estonia     21
8                  Finland     21
9                   France     21
10                 Germany     21
11                  Greece     21
12                 Hungary     21
13                 Ireland     21
14                   Italy     21
15                  Latvia     21
16           Liechtenstein     21
17               Lithuania     21
18              Luxembourg     20
19              Montenegro     11
20             Netherlands     21
21         North Macedonia     16
22                  Norway     21
23                  Poland     21
24                Portugal     21
25                 Romania     21
26                Slovakia     21
27                Slovenia     21
28                   Spain     21
29                  Sweden     21
30             Switzerland     17
31                 Türkiye     21
32                 Ukraine      4
33          United Kingdom     16

In [64]:
df[df['geo'] == 'Poland']

        geo  TIME_PERIOD  Passengers_Mil_KM  km_railways
454  Poland         2004            18430.0      16297.0
455  Poland         2005            17882.0      15859.0
456  Poland         2006            18240.0      16114.0
457  Poland         2007            19524.0      15822.0
458  Poland         2008            19762.0      16354.0
459  Poland         2009            18128.0      16882.0
460  Poland         2010            17485.0      16904.0
461  Poland         2011            17633.0      16888.0
462  Poland         2012            17674.0      17008.0
463  Poland         2013            16659.0      16351.0
464  Poland         2014            15885.0      16112.0
465  Poland         2015            17240.0      16915.0
466  Poland         2016            19067.0      16184.0
467  Poland         2017            20215.0      16331.0
468  Poland         2018                NaN      16452.0
469  Poland         2019                NaN      16519.0
470  Poland         2020                NaN      16475.0
471  Poland         2021                NaN      16427.0
472  Poland         2022                NaN      16499.0
473  Poland         2023                NaN      16541.0
474  Poland         2024                NaN      17288.0

In [65]:
df[df['geo'] == 'Italy']

       geo  TIME_PERIOD  Passengers_Mil_KM  km_railways
281  Italy         2004            49254.0      15916.0
282  Italy         2005            50088.0      16225.0
283  Italy         2006            50185.0      16295.0
284  Italy         2007            49780.0      16335.0
285  Italy         2008            49524.0      16529.0
286  Italy         2009            48124.0      16686.0
287  Italy         2010            47172.0      16704.0
288  Italy         2011                NaN      16726.0
289  Italy         2012            46759.0      16742.0
290  Italy         2013            48739.0      16752.0
291  Italy         2014            49957.0      16722.0
292  Italy         2015            52207.0      16724.0
293  Italy         2016            52178.0      16788.0
294  Italy         2017            53231.0      16787.0
295  Italy         2018            55493.0      16781.0
296  Italy         2019            56586.0      16779.0
297  Italy         2020            22269.0      16782.0
298  Italy         2021            27693.0      16832.0
299  Italy         2022            46498.0      16829.0
300  Italy         2023            54791.0      16832.0
301  Italy         2024            55872.0      16879.0

In [66]:
urlPopulation = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/demo_urespop/1.0?compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'
urlPopulation = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/demo_pjan/1.0/*.*.*.*.*?c[freq]=A&c[unit]=NR&c[age]=TOTAL&c[sex]=T&c[geo]=BE,BG,CZ,DK,DE,EE,IE,EL,ES,FR,FX,HR,IT,CY,LV,LT,LU,HU,MT,NL,AT,PL,PT,RO,SI,SK,FI,SE,IS,LI,NO,CH,UK,BA,ME,MD,MK,GE,AL,RS,TR,UA,XK,AD,BY,MC,RU,SM,AM,AZ&c[TIME_PERIOD]=2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004&compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'

In [67]:
dfPopulation = pd.read_csv(urlPopulation, sep=",", compression="gzip")

In [68]:
dfPopulation

,DATAFLOW,LAST UPDATE,freq,unit,age,sex,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Andorra,2004,72320,NaN,NaN
1,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Andorra,2005,76875,NaN,NaN
2,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Andorra,2006,78549,NaN,NaN
3,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Andorra,2007,81222,NaN,NaN
4,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Andorra,2008,83137,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
989,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Kosovo*,2018,1798506,NaN,NaN
990,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Kosovo*,2019,1795666,NaN,NaN
991,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Kosovo*,2020,1782115,NaN,NaN
992,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Kosovo*,2021,1798186,NaN,NaN
993,ESTAT:DEMO_PJAN(1.0),30/05/26 11:00:00,Annual,Number,Total,Total,Kosovo*,2022,1773971,NaN,NaN

In [69]:
dfPopulation.describe()

       TIME_PERIOD     OBS_VALUE  CONF_STATUS
count   994.000000  9.940000e+02          0.0
mean   2014.048290  1.670366e+07          NaN
std       6.329305  2.552668e+07          NaN
min    2004.000000  2.924100e+04          NaN
25%    2009.000000  2.124639e+06          NaN
50%    2014.000000  5.764980e+06          NaN
75%    2019.000000  1.106978e+07          NaN
max    2025.000000  1.441682e+08          NaN

In [70]:
dfPopulation = dfPopulation.drop("DATAFLOW", axis=1)
dfPopulation = dfPopulation.drop("LAST UPDATE", axis=1)
dfPopulation = dfPopulation.drop("freq", axis=1)
dfPopulation = dfPopulation.drop("unit", axis=1)

In [71]:
dfPopulation

       age    sex      geo  TIME_PERIOD  OBS_VALUE OBS_FLAG  CONF_STATUS
0    Total  Total  Andorra         2004      72320      NaN          NaN
1    Total  Total  Andorra         2005      76875      NaN          NaN
2    Total  Total  Andorra         2006      78549      NaN          NaN
3    Total  Total  Andorra         2007      81222      NaN          NaN
4    Total  Total  Andorra         2008      83137      NaN          NaN
..     ...    ...      ...          ...        ...      ...          ...
989  Total  Total  Kosovo*         2018    1798506      NaN          NaN
990  Total  Total  Kosovo*         2019    1795666      NaN          NaN
991  Total  Total  Kosovo*         2020    1782115      NaN          NaN
992  Total  Total  Kosovo*         2021    1798186      NaN          NaN
993  Total  Total  Kosovo*         2022    1773971      NaN          NaN

[994 rows x 7 columns]

In [72]:
dfPopulation["OBS_FLAG"].unique()

<StringArray>
[nan, 'e', 'b', 'p', 'be', 'ep', 'bep']
Length: 7, dtype: str

In [73]:
df = df.merge(
    dfPopulation[["geo", "TIME_PERIOD", "OBS_VALUE"]],
    on=["geo", "TIME_PERIOD"],
    how="left"
)

In [74]:
df

                geo  TIME_PERIOD  Passengers_Mil_KM  km_railways   OBS_VALUE
0           Austria         2004             8274.0       5675.0   8142573.0
1           Austria         2005             8685.0       5691.0   8201359.0
2           Austria         2006             8907.0       5702.0   8254298.0
3           Austria         2007             9167.0       5702.0   8282984.0
4           Austria         2008            10365.0       5693.0   8307989.0
..              ...          ...                ...          ...         ...
654  United Kingdom         2015            66594.0      14994.0  64853393.0
655  United Kingdom         2016            68010.0      14933.0  65379044.0
656  United Kingdom         2017            68912.0      14990.0  65844142.0
657  United Kingdom         2018            69706.0      15076.0  66273576.0
658  United Kingdom         2019            71823.0      15244.0  66647112.0

[659 rows x 5 columns]

In [75]:
df = df.rename(columns={"OBS_VALUE": "population"})

In [76]:
df

                geo  TIME_PERIOD  Passengers_Mil_KM  km_railways  population
0           Austria         2004             8274.0       5675.0   8142573.0
1           Austria         2005             8685.0       5691.0   8201359.0
2           Austria         2006             8907.0       5702.0   8254298.0
3           Austria         2007             9167.0       5702.0   8282984.0
4           Austria         2008            10365.0       5693.0   8307989.0
..              ...          ...                ...          ...         ...
654  United Kingdom         2015            66594.0      14994.0  64853393.0
655  United Kingdom         2016            68010.0      14933.0  65379044.0
656  United Kingdom         2017            68912.0      14990.0  65844142.0
657  United Kingdom         2018            69706.0      15076.0  66273576.0
658  United Kingdom         2019            71823.0      15244.0  66647112.0

[659 rows x 5 columns]

In [77]:
df[df.isna().any(axis=1)]

                geo  TIME_PERIOD  Passengers_Mil_KM  km_railways  population
21          Belgium         2004             9225.0          NaN  10396421.0
22          Belgium         2005             8510.0          NaN  10445852.0
23          Belgium         2006             8964.0          NaN  10511382.0
24          Belgium         2007             9403.0          NaN  10584534.0
25          Belgium         2008            10139.0          NaN  10666866.0
..              ...          ...                ...          ...         ...
643  United Kingdom         2004            43474.0          NaN  59793759.0
644  United Kingdom         2005            44642.0          NaN  60182050.0
645  United Kingdom         2006            47297.0          NaN  60620361.0
646  United Kingdom         2007            50474.0          NaN  61073279.0
650  United Kingdom         2011            58462.0          NaN  63022532.0

[167 rows x 5 columns]

In [78]:
df[df['geo'] == 'Italy']

       geo  TIME_PERIOD  Passengers_Mil_KM  km_railways  population
281  Italy         2004            49254.0      15916.0  57611990.0
282  Italy         2005            50088.0      16225.0  58044368.0
283  Italy         2006            50185.0      16295.0  58288996.0
284  Italy         2007            49780.0      16335.0  58510725.0
285  Italy         2008            49524.0      16529.0  59001769.0
286  Italy         2009            48124.0      16686.0  59420592.0
287  Italy         2010            47172.0      16704.0  59690316.0
288  Italy         2011                NaN      16726.0  59948497.0
289  Italy         2012            46759.0      16742.0  60105185.0
290  Italy         2013            48739.0      16752.0  60277309.0
291  Italy         2014            49957.0      16722.0  60345917.0
292  Italy         2015            52207.0      16724.0  60295497.0
293  Italy         2016            52178.0      16788.0  60163712.0
294  Italy         2017            53231.0      16787.0  60066734.0
295  Italy         2018            55493.0      16781.0  59937769.0
296  Italy         2019            56586.0      16779.0  59816673.0
297  Italy         2020            22269.0      16782.0  59641488.0
298  Italy         2021            27693.0      16832.0  59236213.0
299  Italy         2022            46498.0      16829.0  59030133.0
300  Italy         2023            54791.0      16832.0  58997201.0
301  Italy         2024            55872.0      16879.0  58971230.0

In [79]:
gdpCapitaUrl = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/sdg_08_10/1.0/*.*.*.*?c[freq]=A&c[unit]=CLV20_EUR_HAB&c[na_item]=B1GQ&c[geo]=BE,BG,CZ,DK,DE,EE,IE,EL,ES,FR,HR,IT,CY,LV,LT,LU,HU,MT,NL,AT,PL,PT,RO,SI,SK,FI,SE,IS,NO,CH,AL,BA,EA19,ME,MK,RS,TR,UK&c[TIME_PERIOD]=2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025&compress=true&format=csvdata&formatVersion=1.0&lang=en&labels=label_only'

In [80]:
dfCapita = pd.read_csv(gdpCapitaUrl, sep=",", compression="gzip")

In [81]:
dfCapita

,DATAFLOW,LAST UPDATE,freq,unit,na_item,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2000,2120,NaN,NaN
1,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2001,2330,NaN,NaN
2,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2002,2440,NaN,NaN
3,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2003,2580,NaN,NaN
4,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Albania,2004,2730,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
932,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2020,7340,NaN,NaN
933,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2021,8130,NaN,NaN
934,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2022,8490,NaN,NaN
935,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2023,8920,NaN,NaN
936,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Türkiye,2024,9220,NaN,NaN

In [82]:
dfCapita[dfCapita['geo'] == 'Italy']

,DATAFLOW,LAST UPDATE,freq,unit,na_item,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
506,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2000,31090,NaN,NaN
507,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2001,31690,NaN,NaN
508,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2002,31720,NaN,NaN
509,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2003,31570,NaN,NaN
510,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2004,31790,NaN,NaN
511,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2005,31850,NaN,NaN
512,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2006,32290,NaN,NaN
513,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2007,32570,NaN,NaN
514,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2008,31990,NaN,NaN
515,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2009,30110,NaN,NaN
516,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2010,30440,NaN,NaN
517,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2011,30550,NaN,NaN
518,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2012,29510,NaN,NaN
519,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2013,28920,NaN,NaN
520,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2014,28910,NaN,NaN
521,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2015,29210,NaN,NaN
522,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2016,29630,NaN,NaN
523,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2017,30160,NaN,NaN
524,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2018,30470,NaN,NaN
525,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2019,30680,NaN,NaN
526,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2020,28100,NaN,NaN
527,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2021,30760,NaN,NaN
528,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2022,32310,NaN,NaN
529,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2023,32630,NaN,NaN
530,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2024,32900,NaN,NaN
531,ESTAT:SDG_08_10(1.0),11/06/26 23:00:00,Annual,"Chain linked volumes (2020), euro per capita",Gross domestic product at market prices,Italy,2025,33080,e,NaN

In [83]:
df = df.merge(
    dfCapita[["geo", "TIME_PERIOD", "OBS_VALUE"]],
    on=["geo", "TIME_PERIOD"],
    how="left"
)

In [84]:
df

,geo,TIME_PERIOD,Passengers_Mil_KM,km_railways,population,OBS_VALUE
0,Austria,2004,8274.0,5675.0,8142573.0,39620.0
1,Austria,2005,8685.0,5691.0,8201359.0,40270.0
2,Austria,2006,8907.0,5702.0,8254298.0,41370.0
3,Austria,2007,9167.0,5702.0,8282984.0,42790.0
4,Austria,2008,10365.0,5693.0,8307989.0,43270.0
...,...,...,...,...,...,...
654,United Kingdom,2015,66594.0,14994.0,64853393.0,NaN
655,United Kingdom,2016,68010.0,14933.0,65379044.0,NaN
656,United Kingdom,2017,68912.0,14990.0,65844142.0,NaN
657,United Kingdom,2018,69706.0,15076.0,66273576.0,NaN
658,United Kingdom,2019,71823.0,15244.0,66647112.0,NaN

In [85]:
df = df.rename(columns={"OBS_VALUE": "GDP_Capita"})

In [86]:
df

,geo,TIME_PERIOD,Passengers_Mil_KM,km_railways,population,GDP_Capita
0,Austria,2004,8274.0,5675.0,8142573.0,39620.0
1,Austria,2005,8685.0,5691.0,8201359.0,40270.0
2,Austria,2006,8907.0,5702.0,8254298.0,41370.0
3,Austria,2007,9167.0,5702.0,8282984.0,42790.0
4,Austria,2008,10365.0,5693.0,8307989.0,43270.0
...,...,...,...,...,...,...
654,United Kingdom,2015,66594.0,14994.0,64853393.0,NaN
655,United Kingdom,2016,68010.0,14933.0,65379044.0,NaN
656,United Kingdom,2017,68912.0,14990.0,65844142.0,NaN
657,United Kingdom,2018,69706.0,15076.0,66273576.0,NaN
658,United Kingdom,2019,71823.0,15244.0,66647112.0,NaN

In [87]:
df[df['km_railways'].isna()]

,geo,TIME_PERIOD,Passengers_Mil_KM,km_railways,population,GDP_Capita
21,Belgium,2004,9225.0,NaN,10396421.0,37440.0
22,Belgium,2005,8510.0,NaN,10445852.0,38100.0
23,Belgium,2006,8964.0,NaN,10511382.0,38810.0
24,Belgium,2007,9403.0,NaN,10584534.0,39950.0
25,Belgium,2008,10139.0,NaN,10666866.0,39810.0
...,...,...,...,...,...,...
643,United Kingdom,2004,43474.0,NaN,59793759.0,NaN
644,United Kingdom,2005,44642.0,NaN,60182050.0,NaN
645,United Kingdom,2006,47297.0,NaN,60620361.0,NaN
646,United Kingdom,2007,50474.0,NaN,61073279.0,NaN
650,United Kingdom,2011,58462.0,NaN,63022532.0,NaN

In [96]:
valid_kms = df.groupby('geo')['Passengers_Mil_KM'].count()
valid_kms[valid_kms < 15]

geo
Belgium                   10
Bosnia and Herzegovina    11
Hungary                   14
Montenegro                11
Ukraine                    4
Name: Passengers_Mil_KM, dtype: int64

In [89]:
df[df['geo'] == 'Poland']

,geo,TIME_PERIOD,Passengers_Mil_KM,km_railways,population,GDP_Capita
454,Poland,2004,18430.0,16297.0,38190608.0,7820.0
455,Poland,2005,17882.0,15859.0,38173835.0,8080.0
456,Poland,2006,18240.0,16114.0,38157055.0,8590.0
457,Poland,2007,19524.0,15822.0,38125479.0,9170.0
458,Poland,2008,19762.0,16354.0,38115641.0,9570.0
459,Poland,2009,18128.0,16882.0,38135876.0,9810.0
460,Poland,2010,17485.0,16904.0,38022869.0,10150.0
461,Poland,2011,17633.0,16888.0,38062718.0,10680.0
462,Poland,2012,17674.0,17008.0,38063792.0,10840.0
463,Poland,2013,16659.0,16351.0,38062535.0,10930.0
464,Poland,2014,15885.0,16112.0,38017856.0,11360.0
465,Poland,2015,17240.0,16915.0,38005614.0,11870.0
466,Poland,2016,19067.0,16184.0,37967209.0,12240.0
467,Poland,2017,20215.0,16331.0,37972964.0,12870.0
468,Poland,2018,NaN,16452.0,37976687.0,13680.0
469,Poland,2019,NaN,16519.0,37972812.0,14310.0
470,Poland,2020,NaN,16475.0,37958138.0,14310.0
471,Poland,2021,NaN,16427.0,37073357.0,15380.0
472,Poland,2022,NaN,16499.0,36889761.0,15840.0
473,Poland,2023,NaN,16541.0,36753736.0,15950.0
474,Poland,2024,NaN,17288.0,36620970.0,16510.0

In [90]:
df['Passengers_Mil_KM'] = df['Passengers_Mil_KM'].interpolate(method='linear', limit=2, limit_direction='forward', limit_area='inside')

In [92]:
df[df['geo'] == 'Poland']

,geo,TIME_PERIOD,Passengers_Mil_KM,km_railways,population,GDP_Capita
454,Poland,2004,18430.000,16297.0,38190608.0,7820.0
455,Poland,2005,17882.000,15859.0,38173835.0,8080.0
456,Poland,2006,18240.000,16114.0,38157055.0,8590.0
457,Poland,2007,19524.000,15822.0,38125479.0,9170.0
458,Poland,2008,19762.000,16354.0,38115641.0,9570.0
459,Poland,2009,18128.000,16882.0,38135876.0,9810.0
460,Poland,2010,17485.000,16904.0,38022869.0,10150.0
461,Poland,2011,17633.000,16888.0,38062718.0,10680.0
462,Poland,2012,17674.000,17008.0,38063792.0,10840.0
463,Poland,2013,16659.000,16351.0,38062535.0,10930.0
464,Poland,2014,15885.000,16112.0,38017856.0,11360.0
465,Poland,2015,17240.000,16915.0,38005614.0,11870.0
466,Poland,2016,19067.000,16184.0,37967209.0,12240.0
467,Poland,2017,20215.000,16331.0,37972964.0,12870.0
468,Poland,2018,18157.125,16452.0,37976687.0,13680.0
469,Poland,2019,16099.250,16519.0,37972812.0,14310.0
470,Poland,2020,NaN,16475.0,37958138.0,14310.0
471,Poland,2021,NaN,16427.0,37073357.0,15380.0
472,Poland,2022,NaN,16499.0,36889761.0,15840.0
473,Poland,2023,NaN,16541.0,36753736.0,15950.0
474,Poland,2024,NaN,17288.0,36620970.0,16510.0